### ISSUE TITLE
Add missing linter

### ISSUE THREAD

**Issue by salamachinas** [ImantasPrecas/iv-invoice-app#2]
Now project don't have any on linter, added one lets us ensure we are following best practises and catch bugs even before release.

Community default choose are:
https://www.npmjs.com/package/eslint-config-standard-with-typescript

**Comment by ImantasPrecas** [comment]
Added linter manually, please check if configuration is ok, if not i will setup with community default choice (saw your suggestion to late :D). Fixed all linting problems.
